# github action to build and publish to google cloud run with
# version as last 11 git has digits
#
name: "Build an publish to Google Container Registry"
on: 
  push:
    branches: 
      - master
  pull_request: 
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: "Sets environment if staging"
      run: echo "ENVIRONMENT=staging" >> $GITHUB_ENV
      if: github.ref != 'refs/heads/master'

    - name: "Sets environment if production"
      run: echo "ENVIRONMENT=production" >> $GITHUB_ENV
      if: github.ref == 'refs/heads/master'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: 'gcloud info'

    - name: Auth in Google Cloud Artifact
      run: 'gcloud auth configure-docker europe-west1-docker.pkg.dev'

    - name: Build and push Docker image
      env:
        IMAGE_NAME: europe-west1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/discord-bot/${{ env.ENVIRONMENT }}
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'discord-bot-production'
        image: 'europe-west1-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/discord-bot/${{ env.ENVIRONMENT }}'
